spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    mode: HTML
  devtools:
    restart:
      trigger-file: .trigger

book:
  name: 好好学习
  author: 无名氏
  isbn: ${random.uuid}
  description: ${book.name}, 这本书不错
