server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: info
    io.sample: debug

  file: logs/dev.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8
    username: devuser
    password: Demo@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true