server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: warn
    io.sample: debug

  file: logs/log.my

book:
  name: 好好学习
  author: 无名氏
  isbn: ${random.uuid}
  description: ${book.name}, 这本书不错