spring:
  thymeleaf:
    mode: HTML
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: devuser
    password: Demo@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    io.sample: debug
#    org.springframework: debug
  pattern:
#    console: "%date [%thread] [%-5level] %logger{40} - %message%n"
    file: "%date [%thread] [%-5level] %logger{40} - %message%n"
  file: logs/dev.log
